"""add image upload to reviews

Revision ID: cf31b7e03e16
Revises: e35a1a306bc3
Create Date: 2024-11-19 08:31:32.990654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf31b7e03e16'
down_revision = 'e35a1a306bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race_review', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
