"""Add race_date to HistoricalRace

Revision ID: e35a1a306bc3
Revises: a9a78db80a3c
Create Date: 2024-11-10 17:06:45.710308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e35a1a306bc3'
down_revision = 'a9a78db80a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_race', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race_date', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_race', schema=None) as batch_op:
        batch_op.drop_column('race_date')

    # ### end Alembic commands ###
